### ISSUE TITLE
Error occurred when executing ExtractOpticalFlow:

### ISSUE THREAD

**Issue by Cedri4** [Sxela/ComfyWarp#1]
I got this on the ComfyUI:
Error occurred when executing ExtractOpticalFlow:

The feature encoder should downsample H and W by 8

File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyWarp\warp_nodes.py", line 28, in get_flow
flow, flow_imgs, edge_mask, occlusion_mask, border_mask = get_flow_and_mask(previous_frame, current_frame, num_flow_updates=20, raft_model=self.raft_model, edge_width=11, dilation=2)
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyWarp\flow_utils.py", line 233, in get_flow_and_mask
flow21 = raft_model(frame2.half(), frame1.half(), num_flow_updates=num_flow_updates)[-1] #flow_bwd
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torchvision\models\optical_flow\raft.py", line 482, in forward
raise ValueError("The feature encoder should downsample H and W by 8")

And this on the terminal:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyWarp\warp_nodes.py", line 28, in get_flow
    flow, flow_imgs, edge_mask, occlusion_mask, border_mask = get_flow_and_mask(previous_frame, current_frame, num_flow_updates=20, raft_model=self.raft_model, edge_width=11, dilation=2)
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyWarp\flow_utils.py", line 233, in get_flow_and_mask
    flow21 = raft_model(frame2.half(), frame1.half(), num_flow_updates=num_flow_updates)[-1] #flow_bwd
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torchvision\models\optical_flow\raft.py", line 482, in forward
    raise ValueError("The feature encoder should downsample H and W by 8")
ValueError: The feature encoder should downsample H and W by 8

Here is the part that has a problem:

![image](https://github.com/Sxela/ComfyWarp/assets/93396286/e8f0bbba-d8df-41b5-8576-b0632e0f2085)
I must have put something wrong but I don't know what.
And the fix is probably already out for the patron members but I ain't one.

**Comment by Sxela** [comment]
You need to add a built-in resize node to resize frames to a divisible by 8 resolution

**Comment by Cedri4** [comment]
![image](https://github.com/Sxela/ComfyWarp/assets/93396286/ec4e9a64-2ec2-4c36-b0a0-6c3e563c9d7b)
Like that?

**Comment by Cedri4** [comment]
I figure it out now I have the same issue with #2 
Here is the terminal output
![image](https://github.com/Sxela/ComfyWarp/assets/93396286/9f2aafce-da3c-4d86-bde0-fc9146767ab3)

**Comment by Sxela** [comment]
Should be fixed in https://github.com/Sxela/ComfyWarp/releases/tag/v0.2.0

**Comment by Cedri4** [comment]
Thanks for the update works well. I am gonna close this issue.
